server:
  port: 8899

eureka:
  instance:
    # 表示设置该服务注册中心的hostname
    hostname: localhost
  client:
    # 是否将eureka自身作为应用注册到eureka注册中心
    # 由于我们目前创建的应用是一个服务注册中心，而不是普通的应用。默认情况下，这个应用会向注册中心（也是它自己）注册它自己，设置为false表示禁止这种默认行为
    register-with-eureka: false
    # 为true时，可以启动，但报异常：Cannot execute request on any known server
    # 表示不去检索其他的服务，因为服务注册中心本身的职责就是维护服务实例，它也不需要去检索其他服务
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/